### ISSUE TITLE
How to train two or more languages simultaneously?

### ISSUE THREAD

**Issue by ScottishFold007** [anhnh2002/XTTSv2-Finetuning-for-New-Languages#2]
Great job! I have a small question: I want to avoid catastrophic forgetting or the ability to handle bilingualism, such as training both Chinese and English simultaneously. Can the language be set to automatically recognize, otherwise, if only one language is set, sentence segmentation for the other language will be problematic.

**Comment by nguyenhoanganh2002** [comment]
> Great job! I have a small question: I want to avoid catastrophic forgetting or the ability to handle bilingualism, such as training both Chinese and English simultaneously. Can the language be set to automatically recognize, otherwise, if only one language is set, sentence segmentation for the other language will be problematic.

That's a good question. I will soon add the option to train multiple languages simultaneously. If the language is not provided, it will be automatically detected through langdetect.

**Comment by ScottishFold007** [comment]
> > Great job! I have a small question: I want to avoid catastrophic forgetting or the ability to handle bilingualism, such as training both Chinese and English simultaneously. Can the language be set to automatically recognize, otherwise, if only one language is set, sentence segmentation for the other language will be problematic.
> 
> That's a good question. I will soon add the option to train multiple languages simultaneously. If the language is not provided, it will be automatically detected through langdetect.
I am training a mix of Chinese and English, and I have added automatic detection logic here:

<img width="759" alt="image" src="https://github.com/user-attachments/assets/91eb6cf5-4319-4aae-853a-03cd92c1bd2c">
def detect_language(sentence):
    chinese_char_pattern = re.compile(r'[\u4e00-\u9fff]')
    english_word_pattern = re.compile(r'\b[A-Za-z]+\b')
    chinese_chars = chinese_char_pattern.findall(sentence)
    english_words = english_word_pattern.findall(sentence)
    if len(chinese_chars) > len(english_words):
        return "zh"
    else:
        return "en"

**Comment by sachin-seisei** [comment]
where is this detect lang code block is located can you tell me??

**Comment by anhnh2002** [comment]
Hi @ScottishFold007, new update supports training multiple datasets https://github.com/anhnh2002/XTTSv2-Finetuning-for-New-Languages/commit/af7a9f4814b3eb0ae3873b00e9521d6434a3b83d
