### ISSUE TITLE
Strange Audio Artifacts in Short Text-to-Speech Conversions

### ISSUE THREAD

**Issue by manhcuong17072002** [anhnh2002/XTTSv2-Finetuning-for-New-Languages#27]
I'm encountering a strange issue with text-to-speech conversion. When I input short phrases like 'Xin chào và hẹn gặp lại', the generated audio sometimes contains peculiar sounds that resemble Chinese. I've attached an audio sample for your reference at [here](https://drive.google.com/file/d/14rzFU0-EkGesMppTLHvQCCDrRnvT5mQm/view?usp=drive_link). This issue is less frequent with longer texts. I suspect it might be due to the random nature of GPT models. Have you ever encountered a similar problem? Any insights would be greatly appreciated.

**Comment by anhnh2002** [comment]
Could you try to infer with `temperature=0.7` and `top_p=0.5`?

**Comment by anhnh2002** [comment]
I guess the issue comes from the training dataset, which does not contain enough short text samples. Additionally, the training data is not cleaned, and there is some noise at the end of some samples in the training dataset.
