### ISSUE TITLE
Think one could use the Facebook Fairseq tts models to generate synthetic data?

### ISSUE THREAD

**Issue by DrewThomasson** [anhnh2002/XTTSv2-Finetuning-for-New-Languages#32]
They support 1107 languages for fairseq tts and it's not terrible but idk.

Was thinking about it but perhaps it's better to have it use real audio of specified language

**Comment by anhnh2002** [comment]
While Fairseq TTS is a viable option, we recommend using XTTS due to superior audio quality. Although Fairseq TTS supports an impressive range of 1107 languages, the overall output quality is not optimal for our needs.

**Comment by DrewThomasson** [comment]
No no I meant to use it to generate synthetic data to train XTTS NOT use fairseq for tts
