### ISSUE TITLE
Ưu tiên hỗ trợ người Việt Nam nhé các pro , dữ liệu 2 file sau metadata_train.csv , metadata_eval.csv giống nhau.Thì nên thêm dữ liệu thế nào cho chuẩn xác

### ISSUE THREAD

**Issue by wpresources** [anhnh2002/XTTSv2-Finetuning-for-New-Languages#33]
Ví dụ mình tác được một thư mục file audio wav rồi. Nhưng format 2 file trên đều audio_file|text|speaker_name
 mình nên chia dữ liệu thế nào

**Comment by anhnh2002** [comment]
Random split thôi bạn, lấy đâu đó tầm 10-20k samples cho tập eval là ổn

**Comment by wpresources** [comment]
À vậy là có thể điền lung tung được nhỉ, mình tưởng có quy luật gì mới chia 2 loại file thế (có ý hỏi lại cho chắc :D)

Mình thấy bạn có chia sẻ một model. Giọng nói có vẻ đến từ cd team , mình thấy chất lượng rất hay , mình quan tâm là làm thế nào, bạn có thể tách được audio_file|text vậy . Có công cụ gì giúp mình làm nó dễ dàng hơn chút không

**Comment by anhnh2002** [comment]
Bạn dùng Whisper để đánh nhãn tự động nhé
