### ISSUE TITLE
 Tên speaker_name sao lại đặt @x @y @z làm thế nào để biết mình nên dùng cái nào vậy?

### ISSUE THREAD

**Issue by baokimtien** [anhnh2002/XTTSv2-Finetuning-for-New-Languages#36]
Và tên file có cần đặt theo quy tắc nào không vậy pro

**Comment by anhnh2002** [comment]
speaker_name là identity của của audio, nhưng mà script hiện tại ko cần dùng đến trường này nên bạn có thể để linh tinh cũng được.
