### ISSUE TITLE
Issue with Incoherent Outputs from Finetuned XTTSv2 Model for Malayalam

### ISSUE THREAD

**Issue by rasheed-aidetic** [anhnh2002/XTTSv2-Finetuning-for-New-Languages#38]
I recently finetuned the XTTSv2 model for Malayalam using ~5 hours of audio-text pairs and trained it for just 3 epochs as a test. However, the outputs are completely incoherent and do not resemble Malayalam or any recognizable language.

I am unsure whether this issue is due to a configuration mismatch (like tokenizer or phoneme set not tailored for Malayalam) or if the limited data and epochs are insufficient even for testing purposes.

Could you please clarify if this is likely a configuration problem or simply due to insufficient training data and epochs? I’d like to avoid retraining unnecessarily without addressing the root cause.

Thank you!

**Comment by anhnh2002** [comment]
I suppose this problem stems from insufficient training data
