### ISSUE TITLE
English seems to degrade after finetuning in new language

### ISSUE THREAD

**Issue by SyGen899** [anhnh2002/XTTSv2-Finetuning-for-New-Languages#39]
Hi thanks so much for the repo, truly appreciate it! I was wondering if you have noticed this or perhaps have some ideas on how to prevent this,  but im training a new language, however when trying to use english from the model those words come out as gibberish, but dont on the base model, I tried to tune the params but it has no effect, in the base model english is fine, but in  my finetune its gibberish. my finetune seems to be learning the new language well, but it seems to be degrading other language capabilities.

**Comment by SyGen899** [comment]
https://github.com/user-attachments/assets/ebebd95a-32dc-4ee4-a316-f6927c7763fe


https://github.com/user-attachments/assets/7ce35d39-711f-498c-b7c1-9208a2578b38

for additional context these are the outputs

**Comment by anhnh2002** [comment]
This is a common issue known as catastrophic forgetting, where fine-tuning on a new language can degrade the model's performance on previously learned languages. In your case, the simplest way is to include English samples in your training data alongside the new language to maintain English capacities.

By the way, I'm planning to implement lightweight finetuning (e.g., LoRA), where each language has a separate LoRA module. In this way, the training data does not need to be further expanded.

**Comment by SyGen899** [comment]
> This is a common issue known as catastrophic forgetting, where fine-tuning on a new language can degrade the model's performance on previously learned languages. In your case, the simplest way is to include English samples in your training data alongside the new language to maintain English capacities.
> 
> By the way, I'm planning to implement lightweight finetuning (e.g., LoRA), where each language has a separate LoRA module. In this way, the training data does not need to be further expanded.

thanks for the response. And looking forward to the lora implementation. very exciting news :D
